USE [master]
GO

/****** Object:  Database [STADB]    Script Date: 25/9/2024 00:46:58 ******/
CREATE DATABASE [STADB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'STADB', FILENAME = N'C:\SQLData\MSSQL16.SQLEXPRESS\MSSQL\DATA\STADB.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'STADB_log', FILENAME = N'C:\SQLData\MSSQL16.SQLEXPRESS\MSSQL\DATA\STADB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [STADB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [STADB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [STADB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [STADB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [STADB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [STADB] SET ARITHABORT OFF 
GO

ALTER DATABASE [STADB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [STADB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [STADB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [STADB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [STADB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [STADB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [STADB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [STADB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [STADB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [STADB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [STADB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [STADB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [STADB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [STADB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [STADB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [STADB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [STADB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [STADB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [STADB] SET  MULTI_USER 
GO

ALTER DATABASE [STADB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [STADB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [STADB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [STADB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [STADB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [STADB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [STADB] SET QUERY_STORE = ON
GO

ALTER DATABASE [STADB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [STADB] SET  READ_WRITE 
GO


